### ISSUE TITLE
Can you use environment variables in the body?

### ISSUE THREAD

**Issue by dawilliams** [renevanosnabrugge/SendEmail-BuildTask#12]
I can't seem to get environment variables to expand in the body.  See below.  

> Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition:

Is this possible or am I doing something wrong?  I've tried $(Agent.Name), $env:Agent.Name etc...

**Comment by renevanosnabrugge** [comment]
Fixed and published a new version to the marketplace! Thanks!
