### ISSUE TITLE
commit message

### ISSUE THREAD

**Issue by Killerkiwi2005** [renevanosnabrugge/SendEmail-BuildTask#14]
It looks like variables work ie
$(Build.Repository.Name)  
$(Build.SourceBranch)  
$(Build.SourceVersion)  
$(Build.QueuedBy)  

Is there a way to get commit message?

**Comment by renevanosnabrugge** [comment]
No not at this moment. Which one would you like with multiple commits ?

I think it is a better option to create a custom task / powershell that gets the message and stores it in a variable. Then use this in the send email task

Verstuurd vanaf mijn iPhone

Op 18 aug. 2017 om 00:45 heeft KillerKiwi <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It looks like variables work ie
$(Build.Repository.Name)
$(Build.SourceBranch)
$(Build.SourceVersion)
$(Build.QueuedBy)

Is there a way to get commit message?
