### ISSUE TITLE
Send Mail task failed recently

### ISSUE THREAD

**Issue by ghost** [renevanosnabrugge/SendEmail-BuildTask#16]
Hi Rene,

I utilize your Send Mail Task and all worked perfectly the last year but now it fails. I created  a VSTS report here
https://developercommunity.visualstudio.com/content/problem/207326/send-mail-task-fails.html

Hope you can help me out.
Thanks
best
Eric

**Comment by renevanosnabrugge** [comment]
Seems like an issue with outlook/live. Task still works for me and other servers..
