### ISSUE TITLE
warning SendEmail using deprecated task execution handler

### ISSUE THREAD

**Issue by kcnighsurf** [renevanosnabrugge/SendEmail-BuildTask#25]
##[warning]Task 'SendEmail' (1.1.1029) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by FlorisDevreese** [comment]
Could be that a rebuild of the extension with the newest `ps_modules/VstsTaskSdk` is enough to resolve this issue.

@renevanosnabrugge
This is something I could do, but I still need you to publish the newer extension version
