### ISSUE TITLE
New PRs waiting

### ISSUE THREAD

**Issue by baronmor** [renevanosnabrugge/SendEmail-BuildTask#3]
Hello,

I added 2 PRs to this repo that are aimed at adding the capability of attaching a single file (the scenario is when there's a build task that generates a release notes and the admin wants to add it to the email notification).

Can you please look at these PRs?

Thanks,

Nimrod

**Comment by renevanosnabrugge** [comment]
Hi!

Thanks for the pull requests. My agenda is quite full this week. I try to merge them in and publish a new version asap. 

Thanks 

Verstuurd vanaf mijn iPhone

**Comment by baronmor** [comment]
cool :) - let me know if you need my help at all
