### ISSUE TITLE
Didn't support for MacOS vm instance in Azure Pipeline

### ISSUE THREAD

**Issue by khopithan** [renevanosnabrugge/SendEmail-BuildTask#46]
Getting error and it says that this plugin supports only windows VM instance. So, is there any other way to use this plugin in MmacOS vm instance azure pipeline

**Comment by hangy** [comment]
This task is currently executed as `PowerShell3`, so it's probably not possible to execute it on non-Windows systems without changing that. I'm not sure if changing [execution](https://github.com/renevanosnabrugge/SendEmail-BuildTask/blob/e7a3f7976c14291df3dcbe170bb14676e17c18dc/SendEmail/task.json#L167-L168) to `PowerShell` would run it in `pwsh` or if it would need to be rewritten in JavaScript for portability. The way that MS have gone with most official tasks is to port them to JS/TS.

**Comment by sannae** [comment]
Hello! As @hangy said, it would be helpful to switch to `PowerShell` - which appears to be supported by the [tasks schema](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json) -and maybe replace the obsolete `Send-MailMessage` with a different cmdlet (I tried with [Mailozaurr](https://github.com/EvotecIT/Mailozaurr)'s `Send-EmailMessage` and it works 🥳).

I had a look at it, but apparently the [VSTS Task SDK Powershell API](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/README.md) seems to support only the `PowerShell3` handler 😢. It looks like there's no ETA for support on PowerShell >= 6.0 (as per [this issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/537)).

I guess the only way is to port it to JavaScript?
