### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by bravirao021** [renevanosnabrugge/SendEmail-BuildTask#49]
I am facing the below error: 
"The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated to send mail. Error: 535 5.7.3 Authentication unsuccessful."

I am providing the right credentials but still getting this error. Can someone please help me fix this?

**Comment by ghost** [comment]
We are also seeing the similar issue in our pipelines as well. 
Appreciate of someone can take a look and suggest the solution. 

##[error]The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM

**Comment by bravirao021** [comment]
@SanjayKumar-V23126 , I was able to resolve the issue by following this link: https://morgantechspace.com/2021/01/the-smtp-server-requires-a-secure-connection-or-the-client.html. Give it a try.
