### ISSUE TITLE
Send email to the user that queued the build

### ISSUE THREAD

**Issue by huntantr** [renevanosnabrugge/SendEmail-BuildTask#8]
Instead of having to enter email addresses, enable the task to send the email to the user that queued it.

**Comment by renevanosnabrugge** [comment]
Good suggestion. Was also thinking about sending it to all committers of the build 

Pick this up after my holidays 

Verstuurd vanaf mijn iPhone

**Comment by huntantr** [comment]
That would work as well. I think if you make those as options it would work well. 

Also, anyway to tie it into the TFS notifications settings that already exist instead of having to enter them? I use onprem and we already have the smtp settings configured.

Thanks.

**Comment by DaveKLloyd** [comment]
I tried to use **$(Build.RequestedForEmail)** in the _To Addresses_ field but it doesn't work. 

Is there something you have to do for build variables to be expanded in the From and To Address fields.

**Comment by zairhenrique** [comment]
I think you should use Get-VstsInput in the Powershell script to make **$(Build.RequestedForEmail)** and others build variables to be expanded.

**Comment by iyerusad** [comment]
Yea supporting build variables is a key scenario to enable.

**Comment by renevanosnabrugge** [comment]
Thanks for all the good suggestions but currently I am swamped with “real” work. I happily accept pull requests though :)

**Comment by renevanosnabrugge** [comment]
Not fixing
