### ISSUE TITLE
Error when not specifying user/pass

### ISSUE THREAD

**Issue by ronniehicks** [renevanosnabrugge/SendEmail-BuildTask#9]
An error is encountered when attempting to use anonymous authentication. Log file below.

[tasklog_8.txt](https://github.com/renevanosnabrugge/SendEmail-BuildTask/files/400294/tasklog_8.txt)

**Comment by adam-drewery** [comment]
i get this as well

**Comment by sumo300** [comment]
This needs to allow anonymous auth as on-prem many times does not require authentication.

**Comment by ronniehicks** [comment]
I see this has been fixed in the code, but I don't know if it has been published to the marketplace yet. @renevanosnabrugge would you prefer I close this issue or you? I don't really want to close it until the marketplace extension has been published with the necessary changes. However, I'm no longer in need of this plug-in so will now stop monitoring this issue.

**Comment by renevanosnabrugge** [comment]
Fixed and published
